<?php

/**
 * @file
 * Primary module hooks for Otp Verify module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */


function registration_phone_verify_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  //throw new Exception('Oh no, an exception! ' . $form_id);
   if ($form_id == 'user_register_form') {
    $form['actions']['submit']['#submit'][] = 'registration_phone_verify_registration';
   }
}

function registration_phone_verify_registration($form,  \Drupal\Core\Form\FormStateInterface $form_state) {

  $verification_code_service = \Drupal::service('registration_phone_verify.verification_code');
  $registration_phone_verify_service = \Drupal::service('registration_phone_verify.send_sms');
  $transaction = \Drupal::database()->startTransaction();
  try {
    // Generate otp code.
    $code = $verification_code_service->storeCodeInDataBase($form_state->getValue('uid'));
    // Get verification message.
    $message = $verification_code_service->getVerificationMessage($code);
    $phone =  $form_state->getValue('field_phone_number')[0]['value'];
    if (is_null($phone)) {
      throw new Exception(t('User do not has phone field value.'));
    }
    // Send sms message.
    $isSent = $registration_phone_verify_service->sendSmsMessage($phone, $message);
    if ($isSent) {
      \Drupal::messenger()->addMessage(t('Sms Message sent successfully'));
      // Redirect to verify form.
      $middleware = \Drupal::service('registration_phone_verify.http_middleware');
      $response = new RedirectResponse(Url::fromRoute('registration_phone_verify.verify')->toString());
      $middleware->setRedirectResponse($response);
    }
  }
  catch (\Exception $ex) {
    $transaction->rollBack();
    \Drupal::messenger()->addError($ex->getMessage());
  }
  unset($transaction);
}